"""The daily blog step. The model no longer writes blog posts or their LinkedIn / dev.to versions: the weekly blog
file is made by a person and uploaded through the dashboard, so this step has nothing to generate. The Slack
approval message (agent.notify.post_blog) and the rows it reads (content_posts, content_variants) stay for that file."""

from datetime import date

from agentkit.log import get_logger

log = get_logger("agent.blog")


async def run(today: date | None = None) -> dict:
    log.info("blog posts are not generated by the model; nothing to do")
    return {"processed": 0, "skipped": 1}
